CREATE TABLE location (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(32)  NOT NULL,
    name  VARCHAR(128) NOT NULL,
    type  VARCHAR(32)  NOT NULL,
    CONSTRAINT uq_location_code UNIQUE (code)
);

CREATE TABLE product (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku   VARCHAR(64)  NOT NULL,
    name  VARCHAR(256) NOT NULL,
    CONSTRAINT uq_product_sku UNIQUE (sku)
);

CREATE TABLE stock_level (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT    NOT NULL REFERENCES product (id),
    location_id  BIGINT    NOT NULL REFERENCES location (id),
    on_hand      INTEGER   NOT NULL,
    version      BIGINT    NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_stock_product_location UNIQUE (product_id, location_id),
    CONSTRAINT ck_stock_non_negative CHECK (on_hand >= 0)
);

-- Append-only ledger. The unique key makes idempotency safe even under concurrent retries.
CREATE TABLE inventory_transaction (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_group  VARCHAR(64)  NOT NULL,
    idempotency_key    VARCHAR(128) NOT NULL,
    type               VARCHAR(32)  NOT NULL,
    product_id         BIGINT       NOT NULL REFERENCES product (id),
    location_id        BIGINT       NOT NULL REFERENCES location (id),
    quantity_delta     INTEGER      NOT NULL,
    balance_after      INTEGER      NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_tx_idempotency UNIQUE (idempotency_key, type)
);

CREATE INDEX ix_tx_product ON inventory_transaction (product_id, id);
